### ISSUE TITLE
use common PropTypes

### ISSUE THREAD

**Issue by DrJekill352** [dzevakov/react-todo-app#4]
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/todo-list/todo-list.js#L28

Старайся избегать использовать PropTypes.array, PropTypes.object, PropTypes.any.
Для этого случая надо использовать PropTypes.arrayOf()

`todos: PropTypes.arrayOf(PropTypes.shape({
            id: PropTypes.number,
            name: PropTypes.string,
            isDone: PropTypes.bool,
)),`

**Comment by dzevakov** [comment]
изменил на 
TodoList.propTypes = {
  todos: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.number,
      name: PropTypes.string,
      isDone: PropTypes.bool,
    })
  ),
  onChangeName: PropTypes.func,
  onToggle: PropTypes.func
}
