### ISSUE TITLE
always add dependency in useEffect

### ISSUE THREAD

**Issue by DrJekill352** [dzevakov/react-todo-app#5]
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/App.js#L13

для useEffect, useMemo, useCallback всегда надо добовлять зависимости. Почитай в документации как это аботает

**Comment by dzevakov** [comment]
React.useEffect(() => {
    localStorage.setItem('todoapp', JSON.stringify(todos))
  }, [todos])
