### ISSUE TITLE
good place for useMemo

### ISSUE THREAD

**Issue by DrJekill352** [dzevakov/react-todo-app#6]
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/todo-item/todo-item.js#L28

При таком коде получается что `taskDoneClass ` пересчитывается при каждом изменении компонента.

Но для таких случаем лучше написать утелитку или использовать библеотека на подобие clsx.
https://github.com/lukeed/clsx#readme

**Comment by dzevakov** [comment]
Добавил утилитку, которая создает имя класса. И с использованием хука React.useMemo создал мемоизированное значение имени класса с указанием флага isDone задачи в качестве зависимости.
