### ISSUE TITLE
better creat function

### ISSUE THREAD

**Issue by DrJekill352** [dzevakov/react-todo-app#7]
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/create-todo/create-todo.js#L26

В даном случае получается что при изменении компонента ты создаёшь новую функцию и передаёшь в props компонентаю Это может ударить по перфомансу

**Comment by dzevakov** [comment]
refactored in todo-item.js, create-todo.js

**Comment by dzevakov** [comment]
Что делать в случае когда нужно передать аргумент 
onChange={() => props.onToggle(props.id)}

**Comment by dzevakov** [comment]
done
