### ISSUE TITLE
Best practices 

### ISSUE THREAD

**Issue by DrJekill352** [dzevakov/react-todo-app#8]
1. Лучше использовать arrow function
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/App.js#L8

2. Проще функции. когда функция состоит из одной строчке после => можно не ставить {}, функция получается более читабельной
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/App.js#L46

3. Контекст прикольно, но лучше стараться его избегать. Контекст вносит неясность в код. Но бывают случаи когда он нужен, например: глубокое погружение значение в компоненты
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/App.js#L61

4. React.Fragment тебе здесь не нужен можешь просто `return todos.map(`
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/todo-list/todo-list.js#L8

5. Если в компоненте не много props можно их сразу серелизовать `TodoList({todos, onChangeName, onToggle}) {`. Это упрощает читабельность кода
https://github.com/dzevakov/react-todo-app/blob/4f63242a32457324daf14ffaf2035584ee6af7f9/src/todo-list/todo-list.js#L6

**Comment by dzevakov** [comment]
1) done
2) check & refactor in app.js, create-todo.js, todo-item.js
3) remove React.Context from this app
4) remove <React.Fragment> from todo-list.js /Line 8
5) done
