### ISSUE TITLE
Data transfer fail

### ISSUE THREAD

**Issue by DrJekill352** [dzevakov/react-todo-app#9]
Проблема в движении даных. В App.js у тебя хранится массив всех ToDo, но в todo-item.js ты можешь менять текст ToDo, но эти изменения остаются внутри todo-item.js и даные в App.js никак не меняются. И если тебе потребуется кудато отправить даные то у тебя потеряются изменения

**Comment by dzevakov** [comment]
Изменения приходят в компонент App. Может слишком запутанна логика, нужно изменить/упростить?
